---
- name: Restart lightdm
  ansible.builtin.systemd_service:
    name: lightdm
    state: restarted

- name: Update grub
  ansible.builtin.command: update-grub
  changed_when: true

- name: Reboot for kernel parameters
  ansible.builtin.reboot:
    reboot_timeout: 300
