---
- name: Converge
  hosts: all
  become: true
  vars:
    jellyfin_admin_password: molecule
    jellyfin_libraries:
      - name: Movies
        type: movies
        paths: [/media/movies/a, /media/movies/b]
    jellyfin_users:
      - name: alice
        password: molecule
  roles:
    - jellyfin
