---
- name: Proxmox hosts
  hosts: proxmox
  roles:
    - role: pve_passthrough  # only for hosts that pass a GPU to a VM
      when: pve_passthrough_devices | default([]) | length > 0
    - pve_storage
    - pve_template
    - pve_vms

- name: Base configuration for every VM
  hosts: vms
  roles:
    - base
    - shares

- name: Jellyfin media servers
  hosts: jellyfin
  roles:
    - jellyfin  # depends on geerlingguy.docker role and gpu

- name: Game streaming hosts
  hosts: gaming
  roles:
    - steam
    - sunshine  # depends on gpu and desktop

- name: Git forges
  hosts: forgejo
  roles:
    - forgejo  # depends on geerlingguy.docker role
